name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Pack Fuji.Core
      run: dotnet pack Fuji.Core/Fuji.Core.csproj -o .
    - name: Pack Fuji.Generator
      run: dotnet pack Fuji.Generator/Fuji.Generator.csproj -o .
    - name: List nuget sources
      run: dotnet nuget list source
    - name: Add local nuget source
      run: dotnet nuget add source . -n Local
    - name: List nuget sources
      run: dotnet nuget list source
    - run: ls -ahl
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
