name: Publish dotnet package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Pack Fuji.Core
        run: dotnet pack Fuji.Core\Fuji.Core.csproj --configuration Release -o .
      - name: Pack Fuji.Generator
        run: dotnet pack Fuji.Generator\Fuji.Generator.csproj --configuration Release -o .
      - name: Publish the packages to NuGet
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN
